name: Format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-24.04
    if: ${{ vars.APK_ONLY == '' }}
    strategy:
      fail-fast: false
      matrix:
        path:
          - 'client'
          - 'server'
          - 'dashboard'
          - 'common'
          - 'tools/wireshark'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@2c659fea724e981e94741c0e7db663982cd7d3f4
      with:
        clang-format-version: '21'
        check-path: ${{ matrix.path }}
