name: Locales
on: [push, pull_request]
jobs:
  locale-check:
    name: Locale check
    runs-on: ubuntu-24.04
    if: ${{ vars.APK_ONLY == '' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install gettext
        pip install polib PyGithub

    - name: Check that .po files are up to date
      run: |
        if [[ "${{github.ref}}" == 'refs/heads/master' ]] ; then
          tools/check_po.py --manage-issues --github-repository "${{ github.repository }}" --github-token "${{ github.token }}"
        else
          tools/check_po.py
        fi
